M48
; DRILL file {KiCad (7.0.0)} date Tue Feb 21 14:29:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-21T14:29:59-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.1969Y-2.2969
X4.1969Y-4.9031
X6.8031Y-2.2969
X6.8031Y-4.9031
T2
X4.55Y-4.5915
X5.0Y-4.5915
X5.975Y-4.6
X6.425Y-4.6
T0
M30
